# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStandardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(db_index=True, max_length=255)),
                ('score', models.DecimalField(decimal_places=10, max_digits=19)),
                ('metadata', jsonfield.fields.JSONField()),
                ('report', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
