# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170805_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codestandarddata',
            name='score',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
