# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commitdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedCommitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('issues_count', models.PositiveIntegerField()),
                ('commit_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CommitData')),
            ],
        ),
    ]
