# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 07:56
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processedcommitdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitdata',
            name='data',
        ),
        migrations.AddField(
            model_name='commitdata',
            name='change_details',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitdata',
            name='lint_report',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedcommitdata',
            name='meta_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
