# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171108_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitdata',
            name='project',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
