# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 10:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commitdata_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.AddIndex(
            model_name='projecttagging',
            index=django.contrib.postgres.indexes.GinIndex(fields=['projects'], name='core_projec_project_7aadfd_gin'),
        ),
    ]
