# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 07:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, size=None),
        ),
    ]
