# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepoDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_of_activity', models.CharField(choices=[('push', 'Push'), ('pullrequest', 'PR')], max_length=20)),
                ('sub_type', models.CharField(blank=True, choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('approval_removed', 'Approval removed'), ('merged', 'Merged'), ('declined', 'Declined'), ('comments_created', 'Comments created'), ('comments_updated', 'Comments updated'), ('comments_deleted', 'Comments deleted')], max_length=20, null=True)),
                ('actor_username', models.CharField(max_length=50)),
                ('actor_display_name', models.CharField(max_length=50)),
                ('project_full_name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, choices=[('O', 'Open'), ('M', 'Merged'), ('D', 'Declined')], max_length=1, null=True)),
                ('content_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('metadata', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='coderepodatabase',
            index=models.Index(fields=['created_at', 'type_of_activity'], name='code_repo_b_created_368c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepodatabase',
            index=models.Index(fields=['created_at', 'state', 'type_of_activity'], name='code_repo_b_created_1eb4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepodatabase',
            index=models.Index(fields=['created_at', 'type_of_activity', 'sub_type'], name='code_repo_b_created_d6741b_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepodatabase',
            index=models.Index(fields=['created_at', 'type_of_activity', 'sub_type', 'actor_username'], name='code_repo_b_created_e184d4_idx'),
        ),
    ]
