# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 13:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitbucketActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_of_activity', models.CharField(choices=[('push', 'Push'), ('pull_request', 'PR')], max_length=20)),
                ('sub_type', models.CharField(choices=[('push', 'Push'), ('pull_request', 'PR')], max_length=20)),
                ('actor_username', models.CharField(db_index=True, max_length=50)),
                ('actor_display_name', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=30)),
                ('project_full_name', models.CharField(db_index=True, max_length=100)),
                ('pull_request_id', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='bitbucket_b_metadat_74b15d_gin'),
        ),
    ]
