# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitbucketactivity',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='bitbucketactivity',
            name='pull_request_id',
        ),
        migrations.AddField(
            model_name='bitbucketactivity',
            name='content_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bitbucketactivity',
            name='state',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('M', 'Merged')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='actor_username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='project_full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('push', 'Push'), ('pull_request', 'PR')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at'], name='bitbucket_b_created_4df059_idx'),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at', 'actor_username'], name='bitbucket_b_created_9c181e_idx'),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at', 'project_full_name'], name='bitbucket_b_created_7a8506_idx'),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['type_of_activity', 'sub_type', 'actor_username'], name='bitbucket_b_type_of_3be7cb_idx'),
        ),
    ]
