# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket', '0002_auto_20180919_0931'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bitbucketactivity',
            name='bitbucket_b_type_of_3be7cb_idx',
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('push', 'Push'), ('pullrequest', 'PR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('push', 'Push'), ('pullrequest', 'PR')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at', 'type_of_activity', 'sub_type', 'actor_username'], name='bitbucket_b_created_51e9e8_idx'),
        ),
    ]
