# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket', '0003_auto_20180920_1209'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bitbucketactivity',
            name='bitbucket_b_metadat_74b15d_gin',
        ),
        migrations.RemoveIndex(
            model_name='bitbucketactivity',
            name='bitbucket_b_created_4df059_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitbucketactivity',
            name='bitbucket_b_created_9c181e_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitbucketactivity',
            name='bitbucket_b_created_7a8506_idx',
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='metadata',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='state',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('M', 'Merged'), ('D', 'Declined')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bitbucketactivity',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('approval_removed', 'Approval removed'), ('merged', 'Merged'), ('declined', 'Declined'), ('comments_created', 'Comments created'), ('comments_updated', 'Comments updated'), ('comments_deleted', 'Comments deleted')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at', 'type_of_activity'], name='bitbucket_b_created_8513d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at', 'state', 'type_of_activity'], name='bitbucket_b_created_1015ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bitbucketactivity',
            index=models.Index(fields=['created_at', 'type_of_activity', 'sub_type'], name='bitbucket_b_created_95ebeb_idx'),
        ),
    ]
